name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: stable
        env:
          # Esto obliga a Buildozer a ser mucho más hablador
          PYTHONUNBUFFERED: 1
          # Configuramos esto para evitar errores de memoria comunes
          JVM_OPTS: "-Xmx2048m"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MiAppAPK
          path: bin/*.apk
        if: always()
