name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer
    steps:
      - uses: actions/checkout@v3

      - name: Build with Buildozer
        run: |
          # Le decimos a buildozer que ignore la advertencia de root
          export BUILDOZER_ALLOW_ROOT=1
          buildozer -v android debug
        env:
          BUILDOZER_ACCEPT_SDK_LICENSE: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MiAppAPK
          path: bin/*.apk
